bingoCliente: bingoCliente.c 
	gcc bingoCliente.c -o bingoCliente

bingoServidor: bingoServidor.c funcionesServidor.c funcionesServidor.h
	gcc funcionesServidor.c bingoServidor.c -o bingoServidor

clean:
	rm *.o